name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-sub-build]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Notify on Telegram
        run: |
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=🚀 GitHub Action triggered in ${{ github.repository }} on branch ${{ github.ref }}"

      - name: Build and Push Multi-Arch Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
          -t ghcr.io/${{ github.actor }}/docker-urnetwork:latest --push .
